### ISSUE TITLE
Getting error while starting app

### ISSUE THREAD

**Issue by AppBankDigital** [Franpastoragusti/oidc-react-app#13]
When i try to run the reactjs app using npm start command and getting error below. I also added .env file.

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.join (path.js:1147:7)
    at noopServiceWorkerMiddleware (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/react-dev-utils/noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/index.js:317:13)
    at /Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/index.js:275:10)
    at launchEditorMiddleware (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/react-dev-utils/errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/index.js:317:13)
    at /Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/index.js:275:10)
    at handleWebpackInternalMiddleware (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/react-dev-utils/evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (/Users/p0s01qm/OneDriveLocal/reactportal/oidc-react-app/node_modules/express/lib/router/layer.js:95:5)

**Comment by cnadolny2s** [comment]
I get the exact same error. I have also added my .env file and set all env variables accordingly. Can you please check that? @Franpastoragusti

**Comment by visen9** [comment]
`yarn upgrade --latest`

@AppBankDigital, @cnadolny2s  You're right, there are some issues on these external library versions. If you update them, you'll solve the problem.

**Comment by saleeb** [comment]
to fix this issue replace "react-scripts": "^3.x.x" with "react-scripts": "^3.4.1"
 and remove node_modules then npm install again it will work 
 Regards
